Upgrade to Rails 5.2

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,56 +1,36 @@
-#!/bin/sh
+#!/usr/bin/env ruby
+require 'fileutils'
+include FileUtils
 
-# Exit if any subcommand fails
-set -e
+# path to your application root.
+APP_ROOT = File.expand_path('..', __dir__)
 
-STEPS=5
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-YELLOW='\033[0;33m'
-NO_COLOR='\033[0m'
-CLEAR_LINE='\r\033[K'
+chdir APP_ROOT do
+  # This script is a starting point to setup your application.
+  # Add necessary setup steps to this file.
 
-# STEP 1
-printf "[1/${STEPS}]  checking dependencies"
+  puts '== Installing dependencies =='
+  system! 'gem install bundler --conservative'
+  system('bundle check') || system!('bundle install')
 
-if ! command -v redis-server > /dev/null; then
-  printf "${CLEAR_LINE}${RED}  You must install redis before setup can continue${NO_COLOR}\n"
-  printf "    You should:\n"
-  printf "      $ brew install redis\n"
-  exit -1
-fi
+  # Install JavaScript dependencies if using Yarn
+  # system('bin/yarn')
 
-if ! command -v psql > /dev/null; then
-  printf "${CLEAR_LINE}${RED}  You must install postgres before setup can continue${NO_COLOR}\n"
-  printf "    You should:\n"
-  printf "      $ brew install postgresql\n"
-  exit -1
-fi
+  # puts "\n== Copying sample files =="
+  # unless File.exist?('config/database.yml')
+  #   cp 'config/database.yml.sample', 'config/database.yml'
+  # end
 
-if ! command -v bundler > /dev/null; then
-  printf "${CLEAR_LINE}${RED}  You must install bundler before setup can continue${NO_COLOR}\n"
-  printf "    You should:\n"
-  printf "      $ gem install bundler\n"
-  exit -1
-fi
+  puts "\n== Preparing database =="
+  system! 'bin/rails db:setup'
 
-# STEP 2
-printf "${CLEAR_LINE}[2/${STEPS}]  installing gems and their dependencies"
-bundle install > /dev/null
+  puts "\n== Removing old logs and tempfiles =="
+  system! 'bin/rails log:clear tmp:clear'
 
-# STEP 3
-printf "${CLEAR_LINE}[3/${STEPS}]  adding remotes"
-git remote add production git@heroku.com:cybertail.git
-
-# STEP 4
-printf "${CLEAR_LINE}[4/${STEPS}]  fetching remotes"
-git fetch --all --quiet > /dev/null
-
-# STEP 5
-printf "${CLEAR_LINE}[5/${STEPS}]  database setup"
-bundle exec rake db:create db:migrate > /dev/null
-bundle exec rake db:seed > /dev/null
-
-# FINISH
-printf "${CLEAR_LINE}[${STEPS}/${STEPS}]${GREEN}  finished!${NO_COLOR}\n"
+  puts "\n== Restarting application server =="
+  system! 'bin/rails restart'
+end
